
/****** Object:  Database [APICrudExample]    Script Date: 22-11-2023 04:58:50 PM ******/
CREATE DATABASE [APICrudExample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'APICrudExample', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\APICrudExample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'APICrudExample_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\APICrudExample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [APICrudExample] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [APICrudExample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [APICrudExample] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [APICrudExample] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [APICrudExample] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [APICrudExample] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [APICrudExample] SET ARITHABORT OFF 
GO
ALTER DATABASE [APICrudExample] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [APICrudExample] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [APICrudExample] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [APICrudExample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [APICrudExample] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [APICrudExample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [APICrudExample] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [APICrudExample] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [APICrudExample] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [APICrudExample] SET  DISABLE_BROKER 
GO
ALTER DATABASE [APICrudExample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [APICrudExample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [APICrudExample] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [APICrudExample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [APICrudExample] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [APICrudExample] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [APICrudExample] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [APICrudExample] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [APICrudExample] SET  MULTI_USER 
GO
ALTER DATABASE [APICrudExample] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [APICrudExample] SET DB_CHAINING OFF 
GO
ALTER DATABASE [APICrudExample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [APICrudExample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [APICrudExample] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [APICrudExample] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [APICrudExample] SET QUERY_STORE = ON
GO
ALTER DATABASE [APICrudExample] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [APICrudExample]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 22-11-2023 04:58:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 22-11-2023 04:58:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](75) NOT NULL,
	[Mail] [nvarchar](75) NOT NULL,
	[PhoneNumber] [nvarchar](50) NOT NULL,
	[Skillsets] [nvarchar](95) NOT NULL,
	[Hobby] [nvarchar](95) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20231121113626_CreateDb', N'8.0.0')
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([Id], [Username], [Mail], [PhoneNumber], [Skillsets], [Hobby]) VALUES (2, N'Sreejith ', N'sreekichu344@gmail.com', N'7558978600', N'Angular,raect.js,dot net', N'Reading,travelling')
GO
INSERT [dbo].[Users] ([Id], [Username], [Mail], [PhoneNumber], [Skillsets], [Hobby]) VALUES (3, N'Lakshmi', N'lak@gmail.com', N'7896523456', N'dot net core web api', N'reading,dancing')
GO
INSERT [dbo].[Users] ([Id], [Username], [Mail], [PhoneNumber], [Skillsets], [Hobby]) VALUES (6, N'Akshay', N'akku@gmail.com', N'4568902345', N'test,test1', N'test2jfjfkfk')
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
USE [master]
GO
ALTER DATABASE [APICrudExample] SET  READ_WRITE 
GO
